id: c4db94a4206f44b3a1aafd288c381521
initial_creation_type: ocr
source_metadata:
  volumes:
    4c29e367b12f435fbf5982efb504ac7f:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
